import { type ReactNode, useEffect } from "react";

import bigmeloLogo from "../assets/bigmelo-logo.png";
import { getAdminSignInUrl } from "../lib/admin-url";

export type LegalLocale = "es" | "en";
type LegalKind = "dataDeletion" | "privacy" | "terms";

type LegalLayoutProps = {
  children: ReactNode;
  eyebrow: string;
  kind: LegalKind;
  locale: LegalLocale;
  title: string;
  updated?: string;
};

const legalCopy = {
  es: {
    dataDeletion: "Eliminación de datos",
    home: "Inicio",
    privacy: "Privacidad",
    signIn: "Ingresar",
    terms: "Términos",
    updated: "Última actualización: 3 de agosto de 2026",
    footer: "© 2026 Bigmelo. Todos los derechos reservados.",
  },
  en: {
    dataDeletion: "Data Deletion",
    home: "Home",
    privacy: "Privacy",
    signIn: "Sign in",
    terms: "Terms",
    updated: "Last updated: August 3, 2026",
    footer: "© 2026 Bigmelo. All rights reserved.",
  },
} satisfies Record<LegalLocale, Record<string, string>>;

const legalPaths = {
  dataDeletion: {
    en: "/data-deletion",
    es: "/eliminacion-datos",
  },
  privacy: {
    en: "/privacy",
    es: "/privacidad",
  },
  terms: {
    en: "/terms",
    es: "/terminos",
  },
} satisfies Record<LegalKind, Record<LegalLocale, string>>;

export function PrivacyPolicy({ locale }: { locale: LegalLocale }) {
  if (locale === "en") {
    return (
      <LegalLayout
        eyebrow="Privacy Policy"
        kind="privacy"
        locale="en"
        title="Bigmelo Privacy Policy"
        updated="Last updated: August 3, 2026"
      >
        <p>
          This policy explains how Bigmelo collects, uses, shares, and protects
          information when a person creates an account, signs in with connected
          providers, creates a profile, uploads an image, records or uploads
          audio, clones a voice, connects social accounts, publishes a profile
          landing page, manages products or catalog content, pays for a plan, or
          chats with an avatar.
        </p>

        <section>
          <h2>1. Information we process</h2>
          <p>We may process the following categories of information:</p>
          <ul>
            <li>
              Account and contact data, such as name, email, user identifiers,
              Google sign-in data when used, contact form messages, phone
              numbers, and support information.
            </li>
            <li>
              Profile content, such as public name, alias, biography, texts,
              links, instructions, contextual knowledge, uploaded files, CV or
              resume information, facts, sources, and product or catalog data.
            </li>
            <li>
              Images, videos, audio files, and voice samples uploaded to create
              or animate an avatar.
            </li>
            <li>
              Generated models, files, or outputs, including animated avatars,
              cloned voices, and audio responses.
            </li>
            <li>
              Visitor messages sent to a profile and responses generated by the
              system.
            </li>
            <li>
              Technical data, such as IP address, device, browser, usage logs,
              errors, login events, notification events, security events,
              cookies, local storage, session storage, analytics tags, and
              anti-abuse verification tokens.
            </li>
            <li>
              Payment, billing, subscription, payment method reference, Wompi
              transaction, purchased-credit balance, reservation, consumption,
              reversal, tariff, or ledger data when you purchase a plan or
              credits. Bigmelo does not need to store full card numbers.
            </li>
            <li>
              Connected integration data, such as Instagram, Meta, TikTok,
              OnlyFans, YouTube channel and video identifiers, titles,
              thumbnails, selected media, captions, profile links, import
              status, and sync history when you connect those services.
            </li>
          </ul>
        </section>

        <section>
          <h2>2. Image, voice, and sensitive data</h2>
          <p>
            Your image, voice, recordings, and voice characteristics may be
            considered biometric data, sensitive data, or specially protected
            information under applicable law. You may only upload your own image
            or voice, or the image or voice of a person who has given you
            explicit, verifiable, and sufficient authorization to create an
            avatar, clone a voice, and publish a conversational profile.
          </p>
          <p>
            You must not upload images, audio, or voices of minors, public
            figures, employees, clients, family members, third parties, or any
            other person unless you have legal authorization for that specific
            use.
          </p>
        </section>

        <section>
          <h2>3. How we use information</h2>
          <p>We use information to:</p>
          <ul>
            <li>
              Create, configure, publish, and maintain conversational profiles.
            </li>
            <li>
              Generate or animate avatars from images, videos, instructions, or
              references.
            </li>
            <li>
              Clone, synthesize, and play an authorized voice in audio
              responses.
            </li>
            <li>
              Understand visitor messages and generate responses consistent with
              the profile information.
            </li>
            <li>
              Provide support, fix errors, and prevent abuse, fraud,
              impersonation, or illegal uses.
            </li>
            <li>
              Measure plan and purchased-credit usage, preserve an auditable
              credit ledger, and administer balances, reservations, payments,
              limits, disputes, and service availability.
            </li>
            <li>
              Authenticate users, keep sessions active, personalize language,
              send notifications, process contact requests, run security
              checks, and remember browser preferences.
            </li>
            <li>
              Connect social or creator-platform accounts, import selected
              content, display links, process product information, and keep
              authorized integrations working.
            </li>
            <li>
              Comply with legal, contractual, regulatory obligations, or valid
              authority requests.
            </li>
          </ul>
        </section>

        <ExternalProviders locale="en" />

        <section>
          <h2>5. Connected accounts, payments, and browser data</h2>
          <p>
            If you sign in with Google, we use the Google account information
            provided to authenticate you, create or maintain your account, and
            secure access. We do not sell Google user data or use it for
            advertising.
          </p>
          <p>
            If you connect Instagram, Meta, TikTok, OnlyFans, YouTube, or similar
            services, we use the connected data only for the features you
            authorize, such as verification, importing selected media or
            captions, showing social links, preparing profile context, and
            keeping integrations synchronized.
          </p>
          <p>
            The YouTube integration uses an application API key to read public
            channel and video metadata; it does not request your YouTube login
            credentials or permission to modify a channel. We store only the
            channel and video references, titles, unmodified thumbnails,
            availability, and the description you provide. YouTube API metadata
            is refreshed or removed within 30 days. Use of this integration is
            also subject to the YouTube API Services Terms of Service and the
            Google Privacy Policy.
          </p>
          <p>
            Payment providers such as Wompi may process payment method tokens,
            transaction references, authorization results, recurring payment
            status, and fraud prevention data. Bigmelo stores the information
            needed to manage plans, credits, invoices, support, disputes, and
            legal records.
          </p>
          <p>
            We may use cookies, local storage, session storage, Cloudflare
            Turnstile verification, Google Analytics 4, and similar browser
            technologies to remember language, maintain sessions, measure
            aggregate usage, protect forms, and prevent abuse. Optional
            analytics is disabled until you accept it. We do not send profile
            names, contact information, payment data, or chat content to Google
            Analytics.
          </p>
        </section>

        <section>
          <h2>6. Public profiles and visitor messages</h2>
          <p>
            When you publish a profile, information marked as public may be
            viewed by anyone with access to the link. Visitors may send messages
            to the avatar; those messages are processed to generate responses
            and may be retained for conversation continuity, security, support,
            audit, and operational improvement of the profile.
          </p>
          <p>
            Do not include confidential information, health data, financial
            data, passwords, identity documents, trade secrets, or information
            you do not have the right to share in public profiles or
            conversations.
          </p>
        </section>

        <section>
          <h2>7. Retention and deletion</h2>
          <p>
            We retain information while your account, profile, landing page,
            voice model, avatar, or commercial relationship is active, and for
            additional time as needed for security, support, legal compliance,
            abuse prevention, dispute resolution, or backups.
          </p>
          <p>
            Public metadata obtained from YouTube API Services is refreshed or
            deleted within 30 calendar days and is removed when you disconnect
            the channel or delete the related video from Bigmelo.
          </p>
          <p>
            You may request deletion of profiles, images, audio files, voice
            models, connected account data, imported media, product catalog
            data, payment references, contact submissions, or personal data.
            Some deletions may take time to appear in backups, technical logs,
            browser storage, analytics systems, payment records, or provider
            systems. We may also retain limited information when necessary by
            law or to investigate abuse, fraud, impersonation, chargebacks, or
            balance disputes.
          </p>
        </section>

        <section>
          <h2>8. Legal bases and consent</h2>
          <p>
            Depending on your jurisdiction, we process data based on your
            consent, performance of a contract, our legitimate interest in
            operating and protecting the service, and compliance with legal
            obligations. Image, voice, and voice cloning features require
            explicit authorization from the person whose image or voice will be
            used.
          </p>
        </section>

        <section>
          <h2>9. Security</h2>
          <p>
            We apply reasonable technical and organizational measures to protect
            data, including access controls, logs, environment separation, and
            incident review. No system is completely secure; you should protect
            your credentials and notify us if you suspect unauthorized use.
          </p>
        </section>

        <section>
          <h2>10. Your rights</h2>
          <p>
            Depending on applicable law, you may request access, correction,
            deletion, portability, objection, restriction of processing, or
            withdrawal of consent. You may also ask that a profile be
            unpublished or that a voice model associated with you be disabled.
          </p>
          <p>
            To exercise rights, contact us at{" "}
            <a href="mailto:privacy@bigmelo.com">privacy@bigmelo.com</a>. We may
            request additional information to verify your identity or authority
            over the image, voice, or profile involved.
          </p>
        </section>

        <section>
          <h2>11. Minors</h2>
          <p>
            The service is not directed to minors. Creating profiles, avatars,
            or cloned voices of minors is not allowed without valid
            authorization from their parents or legal guardians and without
            complying with applicable law.
          </p>
        </section>

        <section>
          <h2>12. Changes</h2>
          <p>
            We may update this policy to reflect legal, technical, or service
            changes. If a change is material, we may notify you through the
            site, email, or within the product. Continued use of the service
            after an update means you accept the current version, unless the law
            requires another mechanism.
          </p>
        </section>
      </LegalLayout>
    );
  }

  return (
    <LegalLayout
      eyebrow="Política de privacidad"
      kind="privacy"
      locale="es"
      title="Política de privacidad de Bigmelo"
      updated="Última actualización: 3 de agosto de 2026"
    >
      <p>
        Esta política explica cómo Bigmelo recopila, usa, comparte y protege
        información cuando una persona crea una cuenta, ingresa con proveedores
        conectados, crea un perfil, sube imagen, graba o carga audio, clona una
        voz, conecta redes sociales, publica un landing de perfil, administra
        productos o catálogo, paga un plan o conversa con un avatar.
      </p>

      <section>
        <h2>1. Información que tratamos</h2>
        <p>Podemos tratar las siguientes categorías de información:</p>
        <ul>
          <li>
            Datos de contacto y cuenta, como nombre, correo, identificadores de
            usuario, datos de ingreso con Google cuando se use, mensajes del
            formulario de contacto, teléfono y datos de soporte.
          </li>
          <li>
            Contenido del perfil, como nombre público, alias, biografía, textos,
            enlaces, instrucciones, conocimiento contextual, archivos subidos,
            hoja de vida o CV, hechos, fuentes y datos de productos o catálogo.
          </li>
          <li>
            Imagen, video, audio y muestras de voz que subas para crear o animar
            un avatar.
          </li>
          <li>
            Modelos, archivos o resultados generados, incluyendo avatar animado,
            voz clonada y respuestas en audio.
          </li>
          <li>
            Mensajes de visitantes al perfil y respuestas generadas por el
            sistema.
          </li>
          <li>
            Datos técnicos, como dirección IP, dispositivo, navegador, registros
            de uso, errores, eventos de ingreso, notificaciones, eventos de
            seguridad, cookies, almacenamiento local, almacenamiento de sesión,
            etiquetas de analítica y tokens de verificación contra abuso.
          </li>
          <li>
            Datos de pago, facturación, suscripción, referencia de medio de
            pago, transacciones de Wompi, saldo, reservas, consumo, reversos,
            tarifas o movimientos de créditos comprados cuando contrates un plan
            o compres créditos. Bigmelo no necesita almacenar números completos
            de tarjeta.
          </li>
          <li>
            Datos de integraciones conectadas, como identificadores de cuentas
              de Instagram, Meta, TikTok, OnlyFans, identificadores de canales y
              videos de YouTube u otras plataformas, tokens de
            acceso, media seleccionada, captions, enlaces de perfil, estado de
            importación e historial de sincronización cuando conectas esos
            servicios.
          </li>
        </ul>
      </section>

      <section>
        <h2>2. Imagen, voz y datos sensibles</h2>
        <p>
          Tu imagen, voz, grabaciones y rasgos de voz pueden considerarse datos
          biométricos, datos sensibles o información especialmente protegida
          según la ley aplicable. Solo debes subir imagen o voz propia, o de una
          persona que te haya dado autorización expresa, verificable y
          suficiente para crear un avatar, clonar voz y publicar un perfil
          conversacional.
        </p>
        <p>
          No debes subir imagen, audio o voz de menores de edad, figuras
          públicas, empleados, clientes, familiares, terceros o cualquier
          persona si no tienes autorización legal para ese uso específico.
        </p>
      </section>

      <section>
        <h2>3. Para qué usamos la información</h2>
        <p>Usamos la información para:</p>
        <ul>
          <li>
            Crear, configurar, publicar y mantener perfiles conversacionales.
          </li>
          <li>
            Generar o animar avatares a partir de imágenes, video, instrucciones
            o referencias.
          </li>
          <li>
            Clonar, sintetizar y reproducir una voz autorizada en respuestas de
            audio.
          </li>
          <li>
            Entender mensajes de visitantes y generar respuestas coherentes con
            la información del perfil.
          </li>
          <li>
            Prestar soporte, corregir errores, prevenir abuso, fraude,
            suplantación o usos ilegales.
          </li>
          <li>
            Medir el uso del plan y de créditos comprados, conservar un registro
            auditable de movimientos y administrar saldos, reservas, pagos,
            límites, disputas y disponibilidad del servicio.
          </li>
          <li>
            Autenticar usuarios, mantener sesiones activas, personalizar idioma,
            enviar notificaciones, procesar solicitudes de contacto, ejecutar
            verificaciones de seguridad y recordar preferencias del navegador.
          </li>
          <li>
            Conectar cuentas sociales o de plataformas de creadores, importar
            contenido seleccionado, mostrar enlaces, procesar información de
            productos y mantener integraciones autorizadas.
          </li>
          <li>
            Cumplir obligaciones legales, contractuales, regulatorias o
            solicitudes válidas de autoridades.
          </li>
        </ul>
      </section>

      <ExternalProviders locale="es" />

      <section>
        <h2>5. Cuentas conectadas, pagos y datos del navegador</h2>
        <p>
          Si ingresas con Google, usamos la información de cuenta que Google
          entregue para autenticarte, crear o mantener tu cuenta y proteger el
          acceso. No vendemos datos de usuario de Google ni los usamos para
          publicidad.
        </p>
        <p>
          Si conectas Instagram, Meta, TikTok, OnlyFans, YouTube o servicios similares,
          usamos los datos conectados solo para las funciones que autorizas,
          como verificación, importación de media o captions seleccionados,
          mostrar enlaces sociales, preparar contexto del perfil y mantener
          integraciones sincronizadas.
        </p>
        <p>
          La integración de YouTube usa una clave de API de la aplicación para
          consultar metadatos públicos de canales y videos; no solicita tus
          credenciales de YouTube ni permisos para modificar un canal. Guardamos
          únicamente referencias del canal y los videos, títulos, miniaturas sin
          modificar, disponibilidad y la descripción que ingreses. Los
          metadatos de la API de YouTube se actualizan o eliminan antes de 30
          días. El uso de esta integración también está sujeto a los Términos de
          Servicio de las APIs de YouTube y a la Política de Privacidad de Google.
        </p>
        <p>
          Proveedores de pago como Wompi pueden procesar tokens de medios de
          pago, referencias de transacción, resultados de autorización, estado
          de pagos recurrentes y datos de prevención de fraude. Bigmelo conserva
          la información necesaria para administrar planes, créditos, facturas,
          soporte, disputas y registros legales.
        </p>
        <p>
          Podemos usar cookies, almacenamiento local, almacenamiento de sesión,
          verificación de Cloudflare Turnstile, Google Analytics 4 y tecnologías
          similares del navegador para recordar idioma, mantener sesiones,
          medir uso agregado, proteger formularios y prevenir abuso. La
          analítica opcional permanece desactivada hasta que la aceptes. No
          enviamos nombres de perfiles, información de contacto, datos de pago
          ni contenido del chat a Google Analytics.
        </p>
      </section>

      <section>
        <h2>6. Perfiles públicos y mensajes de visitantes</h2>
        <p>
          Cuando publicas un perfil, la información marcada como pública puede
          ser vista por cualquier persona con acceso al enlace. Los visitantes
          pueden enviar mensajes al avatar; esos mensajes se procesan para
          generar respuestas y pueden conservarse para continuidad de
          conversación, seguridad, soporte, auditoría y mejora operativa del
          perfil.
        </p>
        <p>
          No incluyas en perfiles públicos ni en conversaciones información
          confidencial, datos de salud, datos financieros, claves, documentos de
          identidad, secretos comerciales o información que no tengas derecho a
          compartir.
        </p>
      </section>

      <section>
        <h2>7. Conservación y eliminación</h2>
        <p>
          Conservamos información mientras tu cuenta, perfil, landing, modelo de
          voz, avatar o relación comercial estén activos, y por el tiempo
          adicional necesario para seguridad, soporte, cumplimiento legal,
          prevención de abuso, resolución de disputas o copias de respaldo.
        </p>
        <p>
          Puedes pedir eliminación de perfiles, imágenes, audios, modelos de
          voz, datos de cuentas conectadas, media importada, catálogo de
          productos, referencias de pago, solicitudes de contacto o datos
          personales.
          Algunas eliminaciones pueden tardar en reflejarse en respaldos,
          registros técnicos, almacenamiento del navegador, analítica, registros
          de pago o sistemas de proveedores. También podemos conservar
          información limitada cuando sea necesario por ley o para investigar
          abuso, fraude, suplantación, contracargos o disputas de saldo.
        </p>
        <p>
          Los metadatos públicos obtenidos de los Servicios de las APIs de
          YouTube se actualizan o eliminan dentro de 30 días calendario y se
          eliminan cuando desconectas el canal o borras el video relacionado de
          Bigmelo.
        </p>
      </section>

      <section>
        <h2>8. Bases legales y consentimiento</h2>
        <p>
          Dependiendo de tu jurisdicción, tratamos datos con base en tu
          consentimiento, la ejecución de un contrato, nuestro interés legítimo
          en operar y proteger el servicio, y el cumplimiento de obligaciones
          legales. Para imagen, voz y clonación de voz, el servicio requiere
          autorización expresa de la persona cuya imagen o voz se usará.
        </p>
      </section>

      <section>
        <h2>9. Seguridad</h2>
        <p>
          Aplicamos medidas técnicas y organizativas razonables para proteger
          los datos, incluyendo controles de acceso, registros, separación de
          ambientes y revisión de incidentes. Ningún sistema es completamente
          seguro; debes proteger tus credenciales y avisarnos si sospechas uso
          no autorizado.
        </p>
      </section>

      <section>
        <h2>10. Tus derechos</h2>
        <p>
          Según la ley aplicable, puedes solicitar acceso, corrección,
          eliminación, portabilidad, oposición, limitación del tratamiento o
          retiro de consentimiento. También puedes pedir que un perfil deje de
          estar publicado o que se desactive un modelo de voz asociado a ti.
        </p>
        <p>
          Para ejercer derechos, contáctanos en{" "}
          <a href="mailto:privacy@bigmelo.com">privacy@bigmelo.com</a>. Podemos
          pedir información adicional para verificar tu identidad o autoridad
          sobre la imagen, voz o perfil involucrado.
        </p>
      </section>

      <section>
        <h2>11. Menores de edad</h2>
        <p>
          El servicio no está dirigido a menores. No se permite crear perfiles,
          avatares o voces clonadas de menores sin autorización válida de sus
          padres o representantes legales y sin cumplir la ley aplicable.
        </p>
      </section>

      <section>
        <h2>12. Cambios</h2>
        <p>
          Podemos actualizar esta política para reflejar cambios legales,
          técnicos o del servicio. Si el cambio es material, podremos
          notificarlo por el sitio, correo o dentro del producto. El uso
          continuado del servicio después de una actualización implica
          aceptación de la versión vigente, salvo que la ley exija otro
          mecanismo.
        </p>
      </section>
    </LegalLayout>
  );
}

export function DataDeletionInstructions({ locale }: { locale: LegalLocale }) {
  if (locale === "en") {
    return (
      <LegalLayout
        eyebrow="User Data Deletion"
        kind="dataDeletion"
        locale="en"
        title="Bigmelo User Data Deletion Instructions"
        updated="Last updated: August 3, 2026"
      >
        <p>
          This page explains how to request deletion of personal data processed
          by Bigmelo. It also serves as Bigmelo's user data deletion
          instructions URL for Meta, Facebook, Instagram, TikTok, or related
          integrations.
        </p>

        <section>
          <h2>1. Data you may ask us to delete</h2>
          <p>
            You may request deletion of information associated with your Bigmelo
            account or profile, including:
          </p>
          <ul>
            <li>
              Account and contact information, such as name, email, and account
              identifiers, Google sign-in data, phone numbers, contact form
              submissions, and support records.
            </li>
            <li>
              Profile pages, aliases, biographies, contextual information,
              social links, CV or resume information, uploaded files, facts,
              sources, product catalog information, imported product images, and
              public profile content.
            </li>
            <li>
              Images, videos, audio files, voice samples, generated avatar
              files, and generated audio files.
            </li>
            <li>
              Connected integration data, such as Instagram, Meta, TikTok, or YouTube
              account identifiers, OnlyFans or similar platform identifiers,
              access tokens, synced media, captions, selected media notes, and
              sync history.
            </li>
            <li>
              Payment-related Bigmelo records, such as Wompi transaction
              references, payment source references, subscription status,
              invoice metadata, credits, and plan history, except records that
              must be retained for legal, tax, fraud, dispute, or accounting
              reasons.
            </li>
            <li>
              Notification preferences, in-app notification records, login
              events, security events, analytics identifiers, and browser
              storage that Bigmelo controls or can reasonably clear.
            </li>
            <li>
              Visitor chat messages and generated responses associated with
              profiles you control, where deletion is technically and legally
              available.
            </li>
          </ul>
        </section>

        <section>
          <h2>2. How to request deletion</h2>
          <p>
            Send your request to{" "}
            <a href="mailto:privacy@bigmelo.com">privacy@bigmelo.com</a> with
            the subject line "Data deletion request". Include enough information
            for us to find and verify the data involved:
          </p>
          <ul>
            <li>The email address used for your Bigmelo account.</li>
            <li>
              The profile alias or profile URL, if your request is about a
              published profile.
            </li>
            <li>
              The connected provider, such as Instagram, Facebook, Meta,
              TikTok, YouTube, Google, OnlyFans, Wompi, or another provider, if your
              request relates to an integration or payment.
            </li>
            <li>
              A clear description of what you want deleted: account, profile,
              media, voice data, chats, products, contact submissions,
              integration data, payment references, browser data, or all
              available data.
            </li>
          </ul>
          <p>
            If a deletion option is available inside the Bigmelo product, you
            may also use that option. We may still contact you to confirm
            identity, authority, or scope.
          </p>
        </section>

        <section>
          <h2>3. Removing connected provider access</h2>
          <p>
            If you connected a Google, Meta, Facebook, Instagram, Threads,
            TikTok, YouTube, OnlyFans, or similar account to Bigmelo, you can remove
            Bigmelo's access from the provider account settings or connected app
            settings. Removing access stops future access by Bigmelo, but you
            should also send us a deletion request if you want previously synced
            data removed from Bigmelo systems.
          </p>
          <p>
            Payment methods, payment source tokens, and transaction data may
            also need to be managed through Wompi or the applicable payment
            provider. We can delete or disable Bigmelo-side payment references
            when legally and operationally available, but payment processors may
            retain their own records under their policies and legal duties.
          </p>
        </section>

        <section>
          <h2>4. Verification and processing time</h2>
          <p>
            We may ask for additional information to verify that you own the
            account, control the profile, or have authority over the image,
            voice, or connected integration. We will process valid requests
            within a reasonable period required by applicable law and
            operational constraints.
          </p>
        </section>

        <section>
          <h2>5. What may be retained</h2>
          <p>
            Some information may be retained for a limited period when necessary
            for legal compliance, payment records, security, fraud prevention,
            dispute resolution, abuse investigations, backups, or technical
            logs. Provider systems, analytics stores, browser storage, payment
            processors, and backups may reflect deletions on different
            timelines. We may also retain aggregated or anonymized information
            that no longer identifies you.
          </p>
          <p>
            Deleting the Bigmelo account closes its purchased-credit wallet and
            permanently forfeits any unused balance, subject to mandatory
            consumer law. We may retain limited payment and credit-ledger records
            when required to document transactions, reversals, taxes, fraud, or
            disputes.
          </p>
        </section>

        <section>
          <h2>6. Contact</h2>
          <p>
            For questions about this process or to follow up on a request,
            contact <a href="mailto:privacy@bigmelo.com">privacy@bigmelo.com</a>
            .
          </p>
        </section>
      </LegalLayout>
    );
  }

  return (
    <LegalLayout
      eyebrow="Eliminación de datos de usuario"
      kind="dataDeletion"
      locale="es"
      title="Instrucciones para eliminación de datos de usuario en Bigmelo"
      updated="Última actualización: 3 de agosto de 2026"
    >
      <p>
        Esta página explica cómo solicitar la eliminación de datos personales
        tratados por Bigmelo. También sirve como URL de instrucciones de
        eliminación de datos de usuario para Meta, Facebook, Instagram, TikTok u
        otras integraciones relacionadas.
      </p>

      <section>
        <h2>1. Datos que puedes pedir que eliminemos</h2>
        <p>
          Puedes solicitar la eliminación de información asociada a tu cuenta o
          perfil de Bigmelo, incluyendo:
        </p>
        <ul>
          <li>
            Datos de cuenta y contacto, como nombre, correo e identificadores de
            usuario, datos de ingreso con Google, teléfonos, solicitudes del
            formulario de contacto y registros de soporte.
          </li>
          <li>
            Páginas de perfil, alias, biografías, información contextual,
            enlaces sociales, hoja de vida o CV, archivos subidos, hechos,
            fuentes, información de catálogo de productos, imágenes importadas
            de productos y contenido público del perfil.
          </li>
          <li>
            Imágenes, videos, audios, muestras de voz, archivos de avatar
            generados y respuestas de audio generadas.
          </li>
          <li>
            Datos de integraciones conectadas, como identificadores de
            Instagram, Meta, TikTok o YouTube, identificadores de OnlyFans o plataformas
            similares, tokens de acceso, media sincronizada, captions,
            observaciones de contenido seleccionado e historial de
            sincronización.
          </li>
          <li>
            Registros de pago en Bigmelo, como referencias de transacciones de
            Wompi, referencias de fuentes de pago, estado de suscripción,
            metadatos de factura, créditos e historial de planes, salvo
            registros que deban conservarse por razones legales, tributarias, de
            fraude, disputas o contabilidad.
          </li>
          <li>
            Preferencias de notificación, registros de notificaciones internas,
            eventos de ingreso, eventos de seguridad, identificadores de
            analítica y almacenamiento del navegador que Bigmelo controle o
            pueda borrar razonablemente.
          </li>
          <li>
            Mensajes de visitantes y respuestas generadas asociadas a perfiles
            que controlas, cuando la eliminación sea técnica y legalmente
            posible.
          </li>
        </ul>
      </section>

      <section>
        <h2>2. Cómo solicitar la eliminación</h2>
        <p>
          Envía tu solicitud a{" "}
          <a href="mailto:privacy@bigmelo.com">privacy@bigmelo.com</a> con el
          asunto "Solicitud de eliminación de datos". Incluye suficiente
          información para ubicar y verificar los datos involucrados:
        </p>
        <ul>
          <li>El correo usado en tu cuenta de Bigmelo.</li>
          <li>
            El alias o URL del perfil, si la solicitud se relaciona con un
            perfil publicado.
          </li>
          <li>
            El proveedor conectado, como Instagram, Facebook, Meta, TikTok o
            YouTube, si la solicitud se relaciona con una integración, o Google, OnlyFans,
            Wompi u otro proveedor si la solicitud se relaciona con ingreso,
            integración o pago.
          </li>
          <li>
            Una descripción clara de lo que quieres eliminar: cuenta, perfil,
            media, datos de voz, chats, productos, solicitudes de contacto,
            datos de integración, referencias de pago, datos del navegador o
            todos los datos disponibles.
          </li>
        </ul>
        <p>
          Si existe una opción de eliminación dentro del producto Bigmelo,
          también puedes usarla. Podemos contactarte para confirmar identidad,
          autoridad o alcance de la solicitud.
        </p>
      </section>

      <section>
        <h2>3. Retirar acceso de proveedores conectados</h2>
        <p>
          Si conectaste una cuenta de Google, Meta, Facebook, Instagram, Threads,
          TikTok, YouTube, OnlyFans o similar a Bigmelo, puedes retirar el acceso de
          Bigmelo desde la configuración de tu cuenta del proveedor o desde apps
          conectadas. Retirar el acceso detiene accesos futuros de Bigmelo, pero
          también debes enviarnos una solicitud de eliminación si quieres borrar
          datos previamente sincronizados en sistemas de Bigmelo.
        </p>
        <p>
          Los medios de pago, tokens de fuente de pago y datos de transacción
          también pueden requerir gestión desde Wompi o el proveedor de pagos
          aplicable. Podemos eliminar o desactivar referencias de pago del lado
          de Bigmelo cuando sea legal y operativamente posible, pero los
          procesadores de pago pueden conservar sus propios registros según sus
          políticas y obligaciones legales.
        </p>
      </section>

      <section>
        <h2>4. Verificación y tiempo de atención</h2>
        <p>
          Podemos pedir información adicional para verificar que eres titular de
          la cuenta, controlas el perfil o tienes autoridad sobre la imagen, voz
          o integración conectada. Procesaremos las solicitudes válidas dentro
          del plazo razonable exigido por la ley aplicable y las restricciones
          operativas.
        </p>
      </section>

      <section>
        <h2>5. Información que puede conservarse</h2>
        <p>
          Parte de la información puede conservarse durante un periodo limitado
          cuando sea necesario para cumplimiento legal, registros de pago,
          seguridad, prevención de fraude, resolución de disputas,
          investigaciones de abuso, respaldos o registros técnicos. Los sistemas
          de proveedores, almacenes de analítica, almacenamiento del navegador,
          procesadores de pago y respaldos pueden reflejar eliminaciones en
          tiempos distintos. También podemos conservar información agregada o
          anonimizada que ya no te identifique.
        </p>
        <p>
          Eliminar la cuenta de Bigmelo cierra su billetera de créditos comprados
          y elimina definitivamente cualquier saldo no utilizado, salvo que una
          norma obligatoria de protección al consumidor disponga otra cosa.
          Podemos conservar registros limitados de pagos y movimientos de
          créditos cuando sean necesarios para documentar transacciones,
          reversos, impuestos, fraude o disputas.
        </p>
      </section>

      <section>
        <h2>6. Contacto</h2>
        <p>
          Para preguntas sobre este proceso o seguimiento de una solicitud,
          contáctanos en{" "}
          <a href="mailto:privacy@bigmelo.com">privacy@bigmelo.com</a>.
        </p>
      </section>
    </LegalLayout>
  );
}

export function TermsAndConditions({ locale }: { locale: LegalLocale }) {
  if (locale === "en") {
    return (
      <LegalLayout
        eyebrow="Terms and Conditions"
        kind="terms"
        locale="en"
        title="Bigmelo Terms and Conditions"
        updated="Last updated: August 3, 2026"
      >
        <p>
          These terms govern access to and use of Bigmelo, a platform for
          creating public profiles with animated avatars, authorized cloned
          voices, contextual information, and AI-generated responses.
        </p>

        <section>
          <h2>1. Acceptance</h2>
          <p>
            By creating an account, uploading content, generating an avatar,
            cloning a voice, publishing a profile, or using a profile landing
            page, you accept these terms and our privacy policy. If you do not
            agree, do not use the service.
          </p>
        </section>

        <section>
          <h2>2. Use requirements</h2>
          <p>
            You must have legal capacity to contract and be at least the age of
            majority applicable in your jurisdiction. If you use Bigmelo on
            behalf of a company, client, talent, brand, or third party, you
            represent that you have sufficient authority to bind them and grant
            the permissions described here.
          </p>
        </section>

        <section>
          <h2>3. Authorization over image, voice, and content</h2>
          <p>When you upload content, you represent and warrant that:</p>
          <ul>
            <li>
              You have all rights and permissions needed for the image, video,
              audio, voice, text, and information submitted.
            </li>
            <li>
              The person whose image or voice is used expressly authorized
              avatar creation, voice cloning, and profile publication.
            </li>
            <li>
              The use of the content does not violate privacy, intellectual
              property, image rights, voice rights, labor rights, or third-party
              rights.
            </li>
            <li>
              You are not using the service to impersonate, deceive, defraud,
              harass, or manipulate other people.
            </li>
          </ul>
        </section>

        <section>
          <h2>4. License to operate the service</h2>
          <p>
            You retain your rights in the content you upload. However, you grant
            Bigmelo a worldwide, non-exclusive, royalty-free license to host,
            copy, process, adapt, transmit, display, and use your content as
            needed to create the avatar, clone and reproduce voice, generate
            responses, publish the profile, provide support, prevent abuse, and
            operate the service.
          </p>
          <p>
            This license includes the right to send content to AI, social,
            payment, storage, security, analytics, and other necessary
            subprocessors, including the providers described in the privacy
            policy. If you delete a profile or request deletion, we will stop
            using the content to operate that profile, except for backups, legal
            obligations, security logs, payment records, or uses needed to
            investigate abuse.
          </p>
        </section>

        <section>
          <h2>5. External providers and integrations</h2>
          <p>
            Bigmelo uses third-party services for essential functions, including
            Runway for avatars and visual assets, ElevenLabs for voice and
            audio, OpenAI for message understanding and response generation,
            Google for authentication or platform services, Meta and Instagram,
            TikTok, OnlyFans, YouTube or similar services for connected account
            features,
            Wompi for payments, Cloudflare Turnstile for anti-abuse checks, and
            infrastructure, storage, email, notification, analytics, and logging
            providers.
          </p>
          <p>
            We do not control changes, interruptions, limits, moderation
            decisions, retention rules, or policies of those providers. We may
            suspend, modify, or reject a generation if a provider or our system
            detects legal, technical, security, payment, rights, or policy risk.
          </p>
        </section>

        <section>
          <h2>6. Public profiles and AI responses</h2>
          <p>
            Profile landing pages may be public. You are responsible for
            reviewing the information you publish and keeping it accurate,
            lawful, and authorized. Avatar responses are generated automatically
            from available context and may contain errors, omissions, responses
            similar to other users, or unexpected content.
          </p>
          <p>
            You must not present generated responses as definitive professional
            advice, guaranteed human statements, legal proof, medical diagnosis,
            personalized financial advice, or automated decisions with legal
            effects without competent human review.
          </p>
          <p>
            If you publish social links, product cards, imported media, catalog
            content, or creator-platform content, including Instagram, TikTok,
            OnlyFans, or similar services, you are responsible for having the
            necessary rights, permissions, age restrictions, disclosures, and
            legal basis for that content. Adult or restricted content may only
            be used where it is lawful, consensual, age appropriate, and
            compliant with platform rules. Non-consensual sexual content and any
            content involving minors are prohibited.
          </p>
        </section>

        <section>
          <h2>7. Prohibited uses</h2>
          <p>You may not use Bigmelo to:</p>
          <ul>
            <li>
              Clone voices or use third-party images without express consent.
            </li>
            <li>
              Create misleading deepfakes, impersonation, fraud, phishing,
              extortion, or manipulation.
            </li>
            <li>
              Generate non-consensual sexual content, child exploitation,
              harassment, threats, hate, or violence.
            </li>
            <li>
              Spread electoral, medical, financial, or legal misinformation, or
              falsely attribute statements to a person.
            </li>
            <li>
              Use content protected by intellectual property rights without
              authorization.
            </li>
            <li>
              Bypass limits, extract models, access systems without permission,
              interfere with security, or resell unauthorized access.
            </li>
            <li>
              Upload sensitive third-party data, secrets, passwords, identity
              documents, or information you should not share.
            </li>
          </ul>
        </section>

        <section>
          <h2>8. Credits, plans, and payments</h2>
          <p>
            Some features consume credits or require a plan. Prices, limits,
            expirations, renewals, and included features will be shown on the
            site or in the applicable offer. Unless required by law, payments,
            consumed credits, and services already provided are not refundable.
          </p>
          <p>
            Unless an offer expressly states otherwise, usage limits reset each
            month and unused capacity does not roll over, including when billing
            is annual. The current Starter offer includes up to 1,000 visitor
            messages by text or audio, up to 500 incoming audio messages of no
            more than 30 seconds each, and up to 20,000 characters converted to
            response audio per monthly usage period.
          </p>
          <p>
            Purchased credits are separate from monthly plan capacity. For each
            eligible feature, Bigmelo always consumes the available plan capacity
            first and only then consumes purchased credits. An account&apos;s
            unused purchased-credit balance carries forward across monthly plan
            resets and subscription renewals. It does not expire while the
            account remains open, has no cash value, cannot be transferred, and
            can only be used while the account has an active paid subscription.
            A trial does not include or enable purchased-credit consumption.
          </p>
          <p>
            Purchased credits can extend visitor messages, incoming-audio
            transcription, response-audio generation, voice re-cloning, and new
            avatar image or video generation at the rates shown before purchase.
            The number of active profiles remains limited by the plan and cannot
            be increased with credits. If neither plan capacity nor enough
            purchased credits are available, the affected operation is blocked:
            the microphone is disabled for incoming audio, audio responses fall
            back to text, and other paid generation operations are not started.
          </p>
          <p>
            Credit packages are one-time purchases. We display the package price
            in USD and Wompi processes the charge in COP using the exchange rate
            shown for that purchase. Applicable credit rates are disclosed in
            the account before purchase. Bigmelo may change rates for future
            usage and purchases, but will not retroactively change credits
            already consumed.
          </p>
          <p>
            If a credit payment is refunded, disputed, charged back, or reversed,
            unused credits from that purchase may be removed. If those credits
            were already consumed or reserved, the account may show a
            reversed-payment balance; purchased credits cannot be used again
            until that balance is offset by a valid purchase or released
            reservation. Closing the account permanently forfeits any unused
            purchased credits, subject to mandatory consumer law.
          </p>
          <p>
            Payments may be processed by Wompi or another payment provider. By
            starting a trial, subscription, recurring payment, plan purchase, or
            credit purchase, you authorize the applicable charges and agree that
            the payment provider may tokenize payment sources, validate payment
            methods, process authorizations and captures, report transaction
            status, and run fraud prevention checks. Trials or subscriptions may
            renew automatically unless cancelled before the renewal or trial end
            date shown in the offer or account settings.
          </p>
          <p>
            Bigmelo may change prices for future purchases and renewals. If a
            change affects an active subscription, we will provide at least 30
            calendar days&apos; prior notice stating the new price, currency, and
            effective date. The new price will apply only to renewals after that
            date, never retroactively or during a period already paid. You may
            cancel automatic renewal before the change takes effect without a
            penalty.
          </p>
          <p>
            Before confirming an electronic purchase, we will show the
            applicable plan, billing cycle, displayed price, and total amount to
            be processed. Prices may be displayed in USD. For immediate charges,
            Wompi processes the exact COP amount shown at checkout using the
            exchange rate presented before acceptance. For a trial conversion or
            future renewal, the COP equivalent is calculated using the exchange
            rate applicable on the charge date; a rate shown when starting the
            trial is informational and may change. The payment record will show
            the rate and COP amount actually processed.
          </p>
        </section>

        <section>
          <h2>9. Moderation, suspension, and removal</h2>
          <p>
            We may review, reject, unpublish, suspend, or remove profiles,
            content, voices, avatars, responses, or accounts when we reasonably
            believe there is a violation of these terms, risk of harm, rights
            infringement, impersonation, fraud, technical abuse, provider
            non-compliance, or a legal requirement.
          </p>
        </section>

        <section>
          <h2>10. Intellectual property</h2>
          <p>
            Bigmelo, its design, software, brand, interface, documentation, and
            technology are owned by Bigmelo or its licensors. You may not copy,
            modify, decompile, sell, sublicense, or exploit the service except
            as expressly permitted.
          </p>
        </section>

        <section>
          <h2>11. Availability and changes</h2>
          <p>
            The service may change, degrade, be interrupted, or become
            unavailable due to maintenance, failures, provider limits,
            regulatory changes, or business reasons. We do not guarantee
            continuous availability or that generations will always be correct,
            complete, unique, or suitable for a specific purpose.
          </p>
        </section>

        <section>
          <h2>12. Liability</h2>
          <p>
            You use Bigmelo at your own risk. To the maximum extent permitted by
            law, Bigmelo will not be liable for indirect damages, lost profits,
            data loss, reputational harm, decisions made based on generated
            responses, unauthorized use of content you uploaded, or failures of
            external providers.
          </p>
        </section>

        <section>
          <h2>13. Contact and reports</h2>
          <p>
            To report impersonation, unauthorized use of image or voice,
            intellectual property infringement, illegal content, or legal
            requests, contact us at{" "}
            <a href="mailto:legal@bigmelo.com">legal@bigmelo.com</a>.
          </p>
        </section>

        <section>
          <h2>14. Changes to these terms</h2>
          <p>
            We may update these terms. If a change is material, we may notify
            you through the site, email, or within the product. Continued use of
            the service after an update means you accept the current version,
            unless the law requires another mechanism.
          </p>
        </section>
      </LegalLayout>
    );
  }

  return (
    <LegalLayout
      eyebrow="Términos y condiciones"
      kind="terms"
      locale="es"
      title="Términos y condiciones de Bigmelo"
      updated="Última actualización: 3 de agosto de 2026"
    >
      <p>
        Estos términos regulan el acceso y uso de Bigmelo, una plataforma para
        crear perfiles públicos con avatares animados, voz clonada autorizada,
        información contextual y respuestas generadas por inteligencia
        artificial.
      </p>

      <section>
        <h2>1. Aceptación</h2>
        <p>
          Al crear una cuenta, subir contenido, generar un avatar, clonar una
          voz, publicar un perfil o usar un landing de perfil, aceptas estos
          términos y nuestra política de privacidad. Si no estás de acuerdo, no
          uses el servicio.
        </p>
      </section>

      <section>
        <h2>2. Requisitos de uso</h2>
        <p>
          Debes tener capacidad legal para contratar y, como mínimo, la mayoría
          de edad aplicable en tu jurisdicción. Si usas Bigmelo en nombre de una
          empresa, cliente, talento, marca o tercero, declaras que tienes
          autoridad suficiente para obligarlo y para otorgar los permisos
          descritos aquí.
        </p>
      </section>

      <section>
        <h2>3. Autorización sobre imagen, voz y contenido</h2>
        <p>Al subir contenido declaras y garantizas que:</p>
        <ul>
          <li>
            Tienes todos los derechos y permisos necesarios sobre la imagen,
            video, audio, voz, texto e información enviada.
          </li>
          <li>
            La persona cuya imagen o voz se usa autorizó expresamente la
            creación de avatar, clonación de voz y publicación del perfil.
          </li>
          <li>
            El uso del contenido no viola privacidad, propiedad intelectual,
            derechos de imagen, derechos de voz, derechos laborales ni derechos
            de terceros.
          </li>
          <li>
            No estás usando el servicio para suplantar, engañar, defraudar,
            acosar o manipular a otras personas.
          </li>
        </ul>
      </section>

      <section>
        <h2>4. Licencia para operar el servicio</h2>
        <p>
          Conservas tus derechos sobre el contenido que subes. Sin embargo,
          otorgas a Bigmelo una licencia mundial, no exclusiva y libre de
          regalías para alojar, copiar, procesar, adaptar, transmitir, mostrar y
          usar tu contenido en la medida necesaria para crear el avatar, clonar
          y reproducir voz, generar respuestas, publicar el perfil, prestar
          soporte, prevenir abuso y operar el servicio.
        </p>
        <p>
          Esta licencia incluye el derecho de enviar contenido a proveedores de
          IA, redes sociales, pagos, almacenamiento, seguridad, analítica y otros
          subprocesadores necesarios, incluyendo los proveedores descritos en la
          política de privacidad. Si eliminas un perfil o solicitas eliminación,
          dejaremos de usar el contenido para operar ese perfil, salvo copias de
          respaldo, obligaciones legales, registros de seguridad, registros de
          pago o usos necesarios para investigar abuso.
        </p>
      </section>

      <section>
        <h2>5. Proveedores externos e integraciones</h2>
        <p>
          Bigmelo usa servicios de terceros para funciones esenciales,
          incluyendo Runway para avatar y recursos visuales, ElevenLabs para voz
          y audio, OpenAI para comprensión de mensajes y generación de
          respuestas, Google para autenticación o servicios de plataforma, Meta
          e Instagram, TikTok, OnlyFans, YouTube o servicios similares para
          funciones de cuentas conectadas, Wompi para pagos, Cloudflare
          Turnstile para
          verificaciones contra abuso, y proveedores de infraestructura,
          almacenamiento, correo, notificaciones, analítica y registros.
        </p>
        <p>
          No controlamos cambios, interrupciones, límites, decisiones de
          moderación, reglas de retención o políticas de esos proveedores.
          Podemos suspender, modificar o rechazar una generación si un proveedor
          o nuestro sistema detecta riesgo legal, técnico, de seguridad, pago,
          derechos o políticas.
        </p>
      </section>

      <section>
        <h2>6. Perfiles públicos y respuestas de IA</h2>
        <p>
          Los landings de perfil pueden ser públicos. Eres responsable de
          revisar la información que publiques y de mantenerla exacta, lícita y
          autorizada. Las respuestas del avatar son generadas automáticamente a
          partir del contexto disponible y pueden contener errores, omisiones,
          respuestas similares a las de otros usuarios o contenido no esperado.
        </p>
        <p>
          No debes presentar respuestas generadas como asesoría profesional
          definitiva, declaración humana garantizada, prueba legal, diagnóstico
          médico, recomendación financiera personalizada o decisión automatizada
          con efectos legales sin revisión humana competente.
        </p>
        <p>
          Si publicas enlaces sociales, tarjetas de producto, media importada,
          contenido de catálogo o contenido de plataformas de creadores,
          incluyendo Instagram, TikTok, OnlyFans o servicios similares, eres
          responsable de contar con los derechos, permisos, restricciones de
          edad, avisos y base legal necesarios para ese contenido. El contenido
          adulto o restringido solo puede usarse cuando sea legal, consentido,
          apto para la edad correspondiente y cumpla reglas de plataforma. Está
          prohibido el contenido sexual no consentido y cualquier contenido que
          involucre menores.
        </p>
      </section>

      <section>
        <h2>7. Usos prohibidos</h2>
        <p>No puedes usar Bigmelo para:</p>
        <ul>
          <li>
            Clonar voces o usar imágenes de terceros sin consentimiento expreso.
          </li>
          <li>
            Crear deepfakes engañosos, suplantaciones, fraude, phishing,
            extorsión o manipulación.
          </li>
          <li>
            Generar contenido sexual no consentido, explotación de menores,
            acoso, amenazas, odio o violencia.
          </li>
          <li>
            Difundir desinformación electoral, médica, financiera o legal, o
            atribuir declaraciones falsas a una persona.
          </li>
          <li>
            Usar contenido protegido por propiedad intelectual sin autorización.
          </li>
          <li>
            Intentar eludir límites, extraer modelos, acceder sin permiso,
            interferir con la seguridad o revender acceso no autorizado.
          </li>
          <li>
            Subir datos sensibles de terceros, secretos, contraseñas, documentos
            de identidad o información que no debas compartir.
          </li>
        </ul>
      </section>

      <section>
        <h2>8. Créditos, planes y pagos</h2>
        <p>
          Algunas funciones consumen créditos o requieren un plan. Los precios,
          límites, vencimientos, renovaciones y funciones incluidas se mostrarán
          en el sitio o en la oferta aplicable. Salvo que la ley exija lo
          contrario, pagos, créditos consumidos y servicios ya prestados no son
          reembolsables.
        </p>
        <p>
          Salvo que una oferta indique expresamente algo distinto, los límites de
          uso se reinician cada mes y la capacidad no utilizada no se acumula,
          incluso cuando el cobro sea anual. La oferta Starter vigente incluye
          hasta 1.000 mensajes de visitantes por texto o audio, hasta 500 audios
          entrantes de máximo 30 segundos cada uno y hasta 20.000 caracteres
          convertidos a audio de respuesta por período mensual de uso.
        </p>
        <p>
          Los créditos comprados son independientes de la capacidad mensual del
          plan. Para cada funcionalidad elegible, Bigmelo consume primero la
          capacidad disponible del plan y solo después utiliza los créditos
          comprados. El saldo no utilizado se conserva entre reinicios mensuales
          y renovaciones de la suscripción. No vence mientras la cuenta permanezca
          abierta, no tiene valor en efectivo, no puede transferirse y solo puede
          utilizarse mientras exista una suscripción paga activa. Una prueba no
          incluye ni habilita el consumo de créditos comprados.
        </p>
        <p>
          Los créditos comprados pueden ampliar mensajes de visitantes,
          transcripción de audios entrantes, generación de audio de respuestas,
          nueva clonación de voz y generación de nuevas imágenes o videos de
          avatar, según las tarifas informadas antes de la compra. La cantidad de
          perfiles activos sigue limitada por el plan y no puede aumentarse con
          créditos. Si no existe capacidad del plan ni créditos suficientes, se
          bloquea la operación afectada: se deshabilita el micrófono para audio
          entrante, las respuestas de audio continúan como texto y las demás
          generaciones pagas no se inician.
        </p>
        <p>
          Los paquetes de créditos son compras únicas. Mostramos su precio en USD
          y Wompi procesa el cobro en COP con la tasa de cambio informada para esa
          compra. Las tarifas aplicables se muestran en la cuenta antes de
          comprar. Bigmelo puede cambiar las tarifas para usos y compras futuras,
          pero no modificará retroactivamente los créditos ya consumidos.
        </p>
        <p>
          Si un pago de créditos es reembolsado, disputado, desconocido o
          reversado, podremos retirar los créditos no utilizados de esa compra.
          Si ya fueron consumidos o reservados, la cuenta podrá mostrar un saldo
          por pago reversado y no podrá volver a utilizar créditos comprados hasta
          compensarlo con una compra válida o la liberación de una reserva. El
          cierre de la cuenta elimina definitivamente los créditos comprados no
          utilizados, salvo que una norma obligatoria de protección al consumidor
          disponga otra cosa.
        </p>
        <p>
          Los pagos pueden ser procesados por Wompi u otro proveedor de pagos.
          Al iniciar una prueba, suscripción, pago recurrente, compra de plan o
          compra de créditos, autorizas los cargos aplicables y aceptas que el
          proveedor de pagos pueda tokenizar fuentes de pago, validar medios de
          pago, procesar autorizaciones y capturas, reportar estado de
          transacciones y ejecutar controles de prevención de fraude. Las
          pruebas o suscripciones pueden renovarse automáticamente salvo que se
          cancelen antes de la fecha de renovación o fin de prueba indicada en
          la oferta o configuración de cuenta.
        </p>
        <p>
          Bigmelo podrá modificar los precios aplicables a futuras compras y
          renovaciones. Si un cambio afecta una suscripción activa, informaremos
          con al menos 30 días calendario de anticipación el nuevo precio, la
          moneda y la fecha de entrada en vigor. El nuevo precio se aplicará
          únicamente a renovaciones posteriores a esa fecha, nunca de forma
          retroactiva ni durante un período ya pagado. Podrás cancelar la
          renovación automática antes de que el cambio entre en vigor, sin
          penalidad.
        </p>
        <p>
          Antes de confirmar una compra electrónica mostraremos el plan, el
          ciclo de facturación, el precio anunciado y el monto total que será
          procesado. Los precios pueden mostrarse en USD. Para cobros inmediatos,
          Wompi procesa en COP el monto exacto presentado en el checkout, usando
          la tasa de cambio informada antes de la aceptación. Para la conversión
          de una prueba o una renovación futura, el equivalente en COP se
          calcula con la tasa aplicable en la fecha del cobro; una tasa mostrada
          al iniciar la prueba es informativa y puede cambiar. El comprobante
          indicará la tasa y el monto COP efectivamente procesados.
        </p>
      </section>

      <section>
        <h2>9. Moderación, suspensión y eliminación</h2>
        <p>
          Podemos revisar, rechazar, despublicar, suspender o eliminar perfiles,
          contenido, voces, avatares, respuestas o cuentas cuando creamos
          razonablemente que existe violación de estos términos, riesgo de daño,
          infracción de derechos, suplantación, fraude, abuso técnico,
          incumplimiento de proveedores o requerimiento legal.
        </p>
      </section>

      <section>
        <h2>10. Propiedad intelectual</h2>
        <p>
          Bigmelo, su diseño, software, marca, interfaz, documentación y
          tecnología son propiedad de Bigmelo o sus licenciantes. No puedes
          copiar, modificar, descompilar, vender, sublicenciar o explotar el
          servicio salvo lo permitido expresamente.
        </p>
      </section>

      <section>
        <h2>11. Disponibilidad y cambios</h2>
        <p>
          El servicio puede cambiar, degradarse, interrumpirse o dejar de estar
          disponible por mantenimiento, fallos, límites de proveedores, cambios
          regulatorios o razones comerciales. No garantizamos disponibilidad
          continua ni que las generaciones sean siempre correctas, completas,
          únicas o adecuadas para un fin específico.
        </p>
      </section>

      <section>
        <h2>12. Responsabilidad</h2>
        <p>
          Usas Bigmelo bajo tu responsabilidad. En la máxima medida permitida
          por la ley, Bigmelo no será responsable por daños indirectos, pérdida
          de ganancias, pérdida de datos, daño reputacional, decisiones tomadas
          con base en respuestas generadas, uso no autorizado de contenido que
          subiste o fallos de proveedores externos.
        </p>
      </section>

      <section>
        <h2>13. Contacto y reportes</h2>
        <p>
          Para reportar suplantación, uso no autorizado de imagen o voz,
          infracciones de propiedad intelectual, contenido ilegal o solicitudes
          legales, escríbenos a{" "}
          <a href="mailto:legal@bigmelo.com">legal@bigmelo.com</a>.
        </p>
      </section>

      <section>
        <h2>14. Cambios a estos términos</h2>
        <p>
          Podemos actualizar estos términos. Si el cambio es material, podremos
          notificarlo por el sitio, correo o dentro del producto. El uso
          continuado del servicio después de una actualización implica
          aceptación de la versión vigente, salvo que la ley exija otro
          mecanismo.
        </p>
      </section>
    </LegalLayout>
  );
}

function ExternalProviders({ locale }: { locale: LegalLocale }) {
  if (locale === "en") {
    return (
      <section>
        <h2>4. External providers and integrations</h2>
        <p>
          To operate the service, we use specialized external providers. By
          using Bigmelo, you accept that the content needed to provide the
          service may be sent to these providers:
        </p>
        <ul>
          <li>
            <a href="https://runwayml.com/" rel="noreferrer" target="_blank">
              Runway
            </a>
            , for avatar, video, image, or other visual asset generation or
            animation.
          </li>
          <li>
            <a href="https://elevenlabs.io/" rel="noreferrer" target="_blank">
              ElevenLabs
            </a>
            , for voice cloning, audio processing, and synthetic voice
            generation.
          </li>
          <li>
            <a href="https://openai.com/" rel="noreferrer" target="_blank">
              OpenAI
            </a>
            , for understanding messages, organizing context, and generating
            responses.
          </li>
          <li>
          <a href="https://policies.google.com/privacy" rel="noreferrer" target="_blank">
              Google
            </a>
            , for sign-in, account authentication, analytics, tag management, or
            related platform services when enabled.
          </li>
          <li>
            <a href="https://www.youtube.com/" rel="noreferrer" target="_blank">
              YouTube
            </a>
            , for validating public channels and videos, displaying unmodified
            titles and thumbnails, and playing videos through YouTube's embedded
            player under the{` `}
            <a
              href="https://developers.google.com/youtube/terms/api-services-terms-of-service"
              rel="noreferrer"
              target="_blank"
            >
              YouTube API Services Terms of Service
            </a>
            .
          </li>
          <li>
            <a href="https://www.meta.com/" rel="noreferrer" target="_blank">
              Meta and Instagram
            </a>
            , for connected social accounts, profile links, media selection, and
            account verification features when authorized.
          </li>
          <li>
            <a href="https://www.tiktok.com/" rel="noreferrer" target="_blank">
              TikTok
            </a>
            , for connected account verification, selected media imports, and
            related social integration features when authorized.
          </li>
          <li>
            <a href="https://wompi.com/" rel="noreferrer" target="_blank">
              Wompi
            </a>
            , for payment processing, payment source tokens, transaction status,
            fraud prevention, and recurring payment operations.
          </li>
          <li>
            <a href="https://www.cloudflare.com/" rel="noreferrer" target="_blank">
              Cloudflare
            </a>
            , for Turnstile verification and abuse prevention on public forms.
          </li>
          <li>
            Infrastructure, storage, email, notification, analytics, and logging
            providers, for hosting, backups, media storage, support, operations,
            and service reliability.
          </li>
        </ul>
        <p>
          Each provider processes data according to its own terms, privacy
          policies, security measures, processing locations, and retention
          rules. We may change, add, or replace providers when necessary to
          maintain or improve the service.
        </p>
      </section>
    );
  }

  return (
    <section>
      <h2>4. Proveedores externos e integraciones</h2>
      <p>
        Para operar el servicio usamos proveedores externos especializados. Al
        usar Bigmelo, aceptas que el contenido necesario pueda enviarse a estos
        proveedores para prestar el servicio:
      </p>
      <ul>
        <li>
          <a href="https://runwayml.com/" rel="noreferrer" target="_blank">
            Runway
          </a>
          , para generación o animación de avatar, video, imagen u otros
          recursos visuales.
        </li>
        <li>
          <a href="https://elevenlabs.io/" rel="noreferrer" target="_blank">
            ElevenLabs
          </a>
          , para clonación de voz, procesamiento de audio y generación de voz
          sintética.
        </li>
        <li>
          <a href="https://openai.com/" rel="noreferrer" target="_blank">
            OpenAI
          </a>
          , para comprender mensajes, organizar contexto y generar respuestas.
        </li>
        <li>
          <a href="https://policies.google.com/privacy" rel="noreferrer" target="_blank">
            Google
          </a>
          , para ingreso, autenticación de cuenta, analítica, administración de
          etiquetas o servicios relacionados de plataforma cuando estén
          habilitados.
        </li>
        <li>
          <a href="https://www.youtube.com/" rel="noreferrer" target="_blank">
            YouTube
          </a>
          , para validar canales y videos públicos, mostrar títulos y miniaturas
          sin modificar, y reproducir videos mediante el reproductor embebido de
          YouTube conforme a los{` `}
          <a
            href="https://developers.google.com/youtube/terms/api-services-terms-of-service"
            rel="noreferrer"
            target="_blank"
          >
            Términos de Servicio de las APIs de YouTube
          </a>
          .
        </li>
        <li>
          <a href="https://www.meta.com/" rel="noreferrer" target="_blank">
            Meta e Instagram
          </a>
          , para cuentas sociales conectadas, enlaces de perfil, selección de
          media y funciones de verificación de cuenta cuando se autoricen.
        </li>
        <li>
          <a href="https://www.tiktok.com/" rel="noreferrer" target="_blank">
            TikTok
          </a>
          , para verificación de cuentas conectadas, importación de media
          seleccionada y funciones relacionadas de integración social cuando se
          autoricen.
        </li>
        <li>
          <a href="https://wompi.com/" rel="noreferrer" target="_blank">
            Wompi
          </a>
          , para procesamiento de pagos, tokens de fuentes de pago, estado de
          transacciones, prevención de fraude y operaciones de pagos recurrentes.
        </li>
        <li>
          <a href="https://www.cloudflare.com/" rel="noreferrer" target="_blank">
            Cloudflare
          </a>
          , para verificación Turnstile y prevención de abuso en formularios
          públicos.
        </li>
        <li>
          Proveedores de infraestructura, almacenamiento, correo,
          notificaciones, analítica y registros, para alojamiento, respaldos,
          almacenamiento de media, soporte, operación y confiabilidad del
          servicio.
        </li>
      </ul>
      <p>
        Cada proveedor procesa datos conforme a sus propias condiciones,
        políticas de privacidad, medidas de seguridad, ubicaciones de
        procesamiento y reglas de retención. Podemos cambiar, agregar o
        sustituir proveedores cuando sea necesario para mantener o mejorar el
        servicio.
      </p>
    </section>
  );
}

function LegalLayout({
  children,
  eyebrow,
  kind,
  locale,
  title,
  updated,
}: LegalLayoutProps) {
  const copy = legalCopy[locale];
  const dataDeletionPath = legalPaths.dataDeletion[locale];
  const privacyPath = legalPaths.privacy[locale];
  const termsPath = legalPaths.terms[locale];
  const spanishPath = legalPaths[kind].es;
  const englishPath = legalPaths[kind].en;
  const adminSignInUrl = getAdminSignInUrl(locale);

  useEffect(() => {
    document.documentElement.lang = locale;
    document.title = `${title} | Bigmelo`;
    window.scrollTo({ top: 0, behavior: "auto" });
  }, [locale, title]);

  return (
    <main className="legal-page">
      <header className="legal-topbar">
        <a className="brand" href="/" aria-label="Bigmelo">
          <img className="brand-logo" alt="Bigmelo" src={bigmeloLogo} />
        </a>

        <div className="legal-topbar-actions">
          <nav
            className="legal-nav"
            aria-label={
              locale === "es" ? "Navegación legal" : "Legal navigation"
            }
          >
            <a href="/">{copy.home}</a>
            <a href={privacyPath}>{copy.privacy}</a>
            <a href={termsPath}>{copy.terms}</a>
            <a href={dataDeletionPath}>{copy.dataDeletion}</a>
          </nav>

          <a className="admin-link legal-admin-link" href={adminSignInUrl}>
            {copy.signIn}
          </a>

          <div
            className="legal-language-switch"
            aria-label={locale === "es" ? "Idioma" : "Language"}
          >
            <a
              className={locale === "es" ? "is-active" : ""}
              href={spanishPath}
            >
              ES
            </a>
            <a
              className={locale === "en" ? "is-active" : ""}
              href={englishPath}
            >
              EN
            </a>
          </div>
        </div>
      </header>

      <article className="legal-document">
        <p className="eyebrow">{eyebrow}</p>
        <h1>{title}</h1>
        <p className="legal-updated">{updated ?? copy.updated}</p>
        {children}
      </article>

      <footer className="legal-footer">
        <a href="/">Bigmelo</a>
        <span>{copy.footer}</span>
      </footer>
    </main>
  );
}
