import { type ReactNode, useEffect } from 'react';

import bigmeloLogo from '../assets/bigmelo-logo.png';

export type LegalLocale = 'es' | 'en';

type LegalLayoutProps = {
  children: ReactNode;
  eyebrow: string;
  kind: 'privacy' | 'terms';
  locale: LegalLocale;
  title: string;
};

const legalCopy = {
  es: {
    home: 'Inicio',
    privacy: 'Privacidad',
    terms: 'Términos',
    updated: 'Última actualización: 19 de junio de 2026',
    footer: '© 2026 Bigmelo. Todos los derechos reservados.',
  },
  en: {
    home: 'Home',
    privacy: 'Privacy',
    terms: 'Terms',
    updated: 'Last updated: June 19, 2026',
    footer: '© 2026 Bigmelo. All rights reserved.',
  },
} satisfies Record<LegalLocale, Record<string, string>>;

export function PrivacyPolicy({ locale }: { locale: LegalLocale }) {
  if (locale === 'en') {
    return (
      <LegalLayout eyebrow="Privacy Policy" kind="privacy" locale="en" title="Bigmelo Privacy Policy">
        <p>
          This policy explains how Bigmelo collects, uses, shares, and protects information when a
          person creates a profile, uploads an image, records or uploads audio, clones a voice,
          publishes a profile landing page, or chats with an avatar.
        </p>

        <section>
          <h2>1. Information we process</h2>
          <p>We may process the following categories of information:</p>
          <ul>
            <li>Account and contact data, such as name, email, user identifiers, and support information.</li>
            <li>Profile content, such as public name, alias, biography, texts, links, instructions, and context.</li>
            <li>Images, videos, audio files, and voice samples uploaded to create or animate an avatar.</li>
            <li>Generated models, files, or outputs, including animated avatars, cloned voices, and audio responses.</li>
            <li>Visitor messages sent to a profile and responses generated by the system.</li>
            <li>Technical data, such as IP address, device, browser, usage logs, errors, and security events.</li>
            <li>Payment, billing, or credit usage data when you purchase a plan or credits.</li>
          </ul>
        </section>

        <section>
          <h2>2. Image, voice, and sensitive data</h2>
          <p>
            Your image, voice, recordings, and voice characteristics may be considered biometric data,
            sensitive data, or specially protected information under applicable law. You may only upload
            your own image or voice, or the image or voice of a person who has given you explicit,
            verifiable, and sufficient authorization to create an avatar, clone a voice, and publish a
            conversational profile.
          </p>
          <p>
            You must not upload images, audio, or voices of minors, public figures, employees, clients,
            family members, third parties, or any other person unless you have legal authorization for
            that specific use.
          </p>
        </section>

        <section>
          <h2>3. How we use information</h2>
          <p>We use information to:</p>
          <ul>
            <li>Create, configure, publish, and maintain conversational profiles.</li>
            <li>Generate or animate avatars from images, videos, instructions, or references.</li>
            <li>Clone, synthesize, and play an authorized voice in audio responses.</li>
            <li>Understand visitor messages and generate responses consistent with the profile information.</li>
            <li>Provide support, fix errors, and prevent abuse, fraud, impersonation, or illegal uses.</li>
            <li>Measure credit usage and administer plans, payments, limits, and service availability.</li>
            <li>Comply with legal, contractual, regulatory obligations, or valid authority requests.</li>
          </ul>
        </section>

        <ExternalProviders locale="en" />

        <section>
          <h2>5. Public profiles and visitor messages</h2>
          <p>
            When you publish a profile, information marked as public may be viewed by anyone with
            access to the link. Visitors may send messages to the avatar; those messages are processed
            to generate responses and may be retained for conversation continuity, security, support,
            audit, and operational improvement of the profile.
          </p>
          <p>
            Do not include confidential information, health data, financial data, passwords, identity
            documents, trade secrets, or information you do not have the right to share in public
            profiles or conversations.
          </p>
        </section>

        <section>
          <h2>6. Retention and deletion</h2>
          <p>
            We retain information while your account, profile, landing page, voice model, avatar, or
            commercial relationship is active, and for additional time as needed for security, support,
            legal compliance, abuse prevention, dispute resolution, or backups.
          </p>
          <p>
            You may request deletion of profiles, images, audio files, voice models, or personal data.
            Some deletions may take time to appear in backups, technical logs, or provider systems. We
            may also retain limited information when necessary by law or to investigate abuse, fraud, or
            impersonation.
          </p>
        </section>

        <section>
          <h2>7. Legal bases and consent</h2>
          <p>
            Depending on your jurisdiction, we process data based on your consent, performance of a
            contract, our legitimate interest in operating and protecting the service, and compliance
            with legal obligations. Image, voice, and voice cloning features require explicit
            authorization from the person whose image or voice will be used.
          </p>
        </section>

        <section>
          <h2>8. Security</h2>
          <p>
            We apply reasonable technical and organizational measures to protect data, including access
            controls, logs, environment separation, and incident review. No system is completely secure;
            you should protect your credentials and notify us if you suspect unauthorized use.
          </p>
        </section>

        <section>
          <h2>9. Your rights</h2>
          <p>
            Depending on applicable law, you may request access, correction, deletion, portability,
            objection, restriction of processing, or withdrawal of consent. You may also ask that a
            profile be unpublished or that a voice model associated with you be disabled.
          </p>
          <p>
            To exercise rights, contact us at <a href="mailto:privacy@bigmelo.com">privacy@bigmelo.com</a>.
            We may request additional information to verify your identity or authority over the image,
            voice, or profile involved.
          </p>
        </section>

        <section>
          <h2>10. Minors</h2>
          <p>
            The service is not directed to minors. Creating profiles, avatars, or cloned voices of
            minors is not allowed without valid authorization from their parents or legal guardians and
            without complying with applicable law.
          </p>
        </section>

        <section>
          <h2>11. Changes</h2>
          <p>
            We may update this policy to reflect legal, technical, or service changes. If a change is
            material, we may notify you through the site, email, or within the product. Continued use
            of the service after an update means you accept the current version, unless the law requires
            another mechanism.
          </p>
        </section>
      </LegalLayout>
    );
  }

  return (
    <LegalLayout eyebrow="Política de privacidad" kind="privacy" locale="es" title="Política de privacidad de Bigmelo">
      <p>
        Esta política explica cómo Bigmelo recopila, usa, comparte y protege información cuando una
        persona crea un perfil, sube imagen, graba o carga audio, clona una voz, publica un landing
        de perfil o conversa con un avatar.
      </p>

      <section>
        <h2>1. Información que tratamos</h2>
        <p>Podemos tratar las siguientes categorías de información:</p>
        <ul>
          <li>Datos de contacto y cuenta, como nombre, correo, identificadores de usuario y datos de soporte.</li>
          <li>Contenido del perfil, como nombre público, alias, biografía, textos, enlaces, instrucciones y contexto.</li>
          <li>Imagen, video, audio y muestras de voz que subas para crear o animar un avatar.</li>
          <li>Modelos, archivos o resultados generados, incluyendo avatar animado, voz clonada y respuestas en audio.</li>
          <li>Mensajes de visitantes al perfil y respuestas generadas por el sistema.</li>
          <li>Datos técnicos, como dirección IP, dispositivo, navegador, registros de uso, errores y eventos de seguridad.</li>
          <li>Datos de pago, facturación o consumo de créditos cuando contrates un plan o compres créditos.</li>
        </ul>
      </section>

      <section>
        <h2>2. Imagen, voz y datos sensibles</h2>
        <p>
          Tu imagen, voz, grabaciones y rasgos de voz pueden considerarse datos biométricos, datos
          sensibles o información especialmente protegida según la ley aplicable. Solo debes subir
          imagen o voz propia, o de una persona que te haya dado autorización expresa, verificable y
          suficiente para crear un avatar, clonar voz y publicar un perfil conversacional.
        </p>
        <p>
          No debes subir imagen, audio o voz de menores de edad, figuras públicas, empleados,
          clientes, familiares, terceros o cualquier persona si no tienes autorización legal para ese
          uso específico.
        </p>
      </section>

      <section>
        <h2>3. Para qué usamos la información</h2>
        <p>Usamos la información para:</p>
        <ul>
          <li>Crear, configurar, publicar y mantener perfiles conversacionales.</li>
          <li>Generar o animar avatares a partir de imágenes, video, instrucciones o referencias.</li>
          <li>Clonar, sintetizar y reproducir una voz autorizada en respuestas de audio.</li>
          <li>Entender mensajes de visitantes y generar respuestas coherentes con la información del perfil.</li>
          <li>Prestar soporte, corregir errores, prevenir abuso, fraude, suplantación o usos ilegales.</li>
          <li>Medir consumo de créditos, administrar planes, pagos, límites y disponibilidad del servicio.</li>
          <li>Cumplir obligaciones legales, contractuales, regulatorias o solicitudes válidas de autoridades.</li>
        </ul>
      </section>

      <ExternalProviders locale="es" />

      <section>
        <h2>5. Perfiles públicos y mensajes de visitantes</h2>
        <p>
          Cuando publicas un perfil, la información marcada como pública puede ser vista por cualquier
          persona con acceso al enlace. Los visitantes pueden enviar mensajes al avatar; esos mensajes
          se procesan para generar respuestas y pueden conservarse para continuidad de conversación,
          seguridad, soporte, auditoría y mejora operativa del perfil.
        </p>
        <p>
          No incluyas en perfiles públicos ni en conversaciones información confidencial, datos de
          salud, datos financieros, claves, documentos de identidad, secretos comerciales o información
          que no tengas derecho a compartir.
        </p>
      </section>

      <section>
        <h2>6. Conservación y eliminación</h2>
        <p>
          Conservamos información mientras tu cuenta, perfil, landing, modelo de voz, avatar o relación
          comercial estén activos, y por el tiempo adicional necesario para seguridad, soporte,
          cumplimiento legal, prevención de abuso, resolución de disputas o copias de respaldo.
        </p>
        <p>
          Puedes pedir eliminación de perfiles, imágenes, audios, modelos de voz o datos personales.
          Algunas eliminaciones pueden tardar en reflejarse en respaldos, registros técnicos o sistemas
          de proveedores. También podemos conservar información limitada cuando sea necesario por ley o
          para investigar abuso, fraude o suplantación.
        </p>
      </section>

      <section>
        <h2>7. Bases legales y consentimiento</h2>
        <p>
          Dependiendo de tu jurisdicción, tratamos datos con base en tu consentimiento, la ejecución de
          un contrato, nuestro interés legítimo en operar y proteger el servicio, y el cumplimiento de
          obligaciones legales. Para imagen, voz y clonación de voz, el servicio requiere autorización
          expresa de la persona cuya imagen o voz se usará.
        </p>
      </section>

      <section>
        <h2>8. Seguridad</h2>
        <p>
          Aplicamos medidas técnicas y organizativas razonables para proteger los datos, incluyendo
          controles de acceso, registros, separación de ambientes y revisión de incidentes. Ningún
          sistema es completamente seguro; debes proteger tus credenciales y avisarnos si sospechas uso
          no autorizado.
        </p>
      </section>

      <section>
        <h2>9. Tus derechos</h2>
        <p>
          Según la ley aplicable, puedes solicitar acceso, corrección, eliminación, portabilidad,
          oposición, limitación del tratamiento o retiro de consentimiento. También puedes pedir que un
          perfil deje de estar publicado o que se desactive un modelo de voz asociado a ti.
        </p>
        <p>
          Para ejercer derechos, contáctanos en <a href="mailto:privacy@bigmelo.com">privacy@bigmelo.com</a>.
          Podemos pedir información adicional para verificar tu identidad o autoridad sobre la imagen,
          voz o perfil involucrado.
        </p>
      </section>

      <section>
        <h2>10. Menores de edad</h2>
        <p>
          El servicio no está dirigido a menores. No se permite crear perfiles, avatares o voces
          clonadas de menores sin autorización válida de sus padres o representantes legales y sin
          cumplir la ley aplicable.
        </p>
      </section>

      <section>
        <h2>11. Cambios</h2>
        <p>
          Podemos actualizar esta política para reflejar cambios legales, técnicos o del servicio. Si
          el cambio es material, podremos notificarlo por el sitio, correo o dentro del producto. El
          uso continuado del servicio después de una actualización implica aceptación de la versión
          vigente, salvo que la ley exija otro mecanismo.
        </p>
      </section>
    </LegalLayout>
  );
}

export function TermsAndConditions({ locale }: { locale: LegalLocale }) {
  if (locale === 'en') {
    return (
      <LegalLayout eyebrow="Terms and Conditions" kind="terms" locale="en" title="Bigmelo Terms and Conditions">
        <p>
          These terms govern access to and use of Bigmelo, a platform for creating public profiles
          with animated avatars, authorized cloned voices, contextual information, and AI-generated
          responses.
        </p>

        <section>
          <h2>1. Acceptance</h2>
          <p>
            By creating an account, uploading content, generating an avatar, cloning a voice,
            publishing a profile, or using a profile landing page, you accept these terms and our
            privacy policy. If you do not agree, do not use the service.
          </p>
        </section>

        <section>
          <h2>2. Use requirements</h2>
          <p>
            You must have legal capacity to contract and be at least the age of majority applicable in
            your jurisdiction. If you use Bigmelo on behalf of a company, client, talent, brand, or
            third party, you represent that you have sufficient authority to bind them and grant the
            permissions described here.
          </p>
        </section>

        <section>
          <h2>3. Authorization over image, voice, and content</h2>
          <p>When you upload content, you represent and warrant that:</p>
          <ul>
            <li>You have all rights and permissions needed for the image, video, audio, voice, text, and information submitted.</li>
            <li>The person whose image or voice is used expressly authorized avatar creation, voice cloning, and profile publication.</li>
            <li>The use of the content does not violate privacy, intellectual property, image rights, voice rights, labor rights, or third-party rights.</li>
            <li>You are not using the service to impersonate, deceive, defraud, harass, or manipulate other people.</li>
          </ul>
        </section>

        <section>
          <h2>4. License to operate the service</h2>
          <p>
            You retain your rights in the content you upload. However, you grant Bigmelo a worldwide,
            non-exclusive, royalty-free license to host, copy, process, adapt, transmit, display, and
            use your content as needed to create the avatar, clone and reproduce voice, generate
            responses, publish the profile, provide support, prevent abuse, and operate the service.
          </p>
          <p>
            This license includes the right to send content to providers such as Runway, ElevenLabs,
            and OpenAI, and to other necessary subprocessors. If you delete a profile or request
            deletion, we will stop using the content to operate that profile, except for backups, legal
            obligations, security logs, or uses needed to investigate abuse.
          </p>
        </section>

        <section>
          <h2>5. External providers</h2>
          <p>
            Bigmelo uses third-party services for essential functions: Runway for avatars and visual
            assets, ElevenLabs for voice and audio, and OpenAI for message understanding and response
            generation. Your use of the service depends on those providers being available and on your
            content complying with their policies.
          </p>
          <p>
            We do not control changes, interruptions, limits, moderation decisions, retention rules, or
            policies of those providers. We may suspend, modify, or reject a generation if a provider
            or our system detects legal, technical, or security risk.
          </p>
        </section>

        <section>
          <h2>6. Public profiles and AI responses</h2>
          <p>
            Profile landing pages may be public. You are responsible for reviewing the information you
            publish and keeping it accurate, lawful, and authorized. Avatar responses are generated
            automatically from available context and may contain errors, omissions, responses similar
            to other users, or unexpected content.
          </p>
          <p>
            You must not present generated responses as definitive professional advice, guaranteed
            human statements, legal proof, medical diagnosis, personalized financial advice, or
            automated decisions with legal effects without competent human review.
          </p>
        </section>

        <section>
          <h2>7. Prohibited uses</h2>
          <p>You may not use Bigmelo to:</p>
          <ul>
            <li>Clone voices or use third-party images without express consent.</li>
            <li>Create misleading deepfakes, impersonation, fraud, phishing, extortion, or manipulation.</li>
            <li>Generate non-consensual sexual content, child exploitation, harassment, threats, hate, or violence.</li>
            <li>Spread electoral, medical, financial, or legal misinformation, or falsely attribute statements to a person.</li>
            <li>Use content protected by intellectual property rights without authorization.</li>
            <li>Bypass limits, extract models, access systems without permission, interfere with security, or resell unauthorized access.</li>
            <li>Upload sensitive third-party data, secrets, passwords, identity documents, or information you should not share.</li>
          </ul>
        </section>

        <section>
          <h2>8. Credits, plans, and payments</h2>
          <p>
            Some features consume credits or require a plan. Prices, limits, expirations, renewals, and
            included features will be shown on the site or in the applicable offer. Unless required by
            law, payments, consumed credits, expired credits, and services already provided are not
            refundable.
          </p>
        </section>

        <section>
          <h2>9. Moderation, suspension, and removal</h2>
          <p>
            We may review, reject, unpublish, suspend, or remove profiles, content, voices, avatars,
            responses, or accounts when we reasonably believe there is a violation of these terms, risk
            of harm, rights infringement, impersonation, fraud, technical abuse, provider
            non-compliance, or a legal requirement.
          </p>
        </section>

        <section>
          <h2>10. Intellectual property</h2>
          <p>
            Bigmelo, its design, software, brand, interface, documentation, and technology are owned by
            Bigmelo or its licensors. You may not copy, modify, decompile, sell, sublicense, or exploit
            the service except as expressly permitted.
          </p>
        </section>

        <section>
          <h2>11. Availability and changes</h2>
          <p>
            The service may change, degrade, be interrupted, or become unavailable due to maintenance,
            failures, provider limits, regulatory changes, or business reasons. We do not guarantee
            continuous availability or that generations will always be correct, complete, unique, or
            suitable for a specific purpose.
          </p>
        </section>

        <section>
          <h2>12. Liability</h2>
          <p>
            You use Bigmelo at your own risk. To the maximum extent permitted by law, Bigmelo will not
            be liable for indirect damages, lost profits, data loss, reputational harm, decisions made
            based on generated responses, unauthorized use of content you uploaded, or failures of
            external providers.
          </p>
        </section>

        <section>
          <h2>13. Contact and reports</h2>
          <p>
            To report impersonation, unauthorized use of image or voice, intellectual property
            infringement, illegal content, or legal requests, contact us at{' '}
            <a href="mailto:legal@bigmelo.com">legal@bigmelo.com</a>.
          </p>
        </section>

        <section>
          <h2>14. Changes to these terms</h2>
          <p>
            We may update these terms. If a change is material, we may notify you through the site,
            email, or within the product. Continued use of the service after an update means you accept
            the current version, unless the law requires another mechanism.
          </p>
        </section>
      </LegalLayout>
    );
  }

  return (
    <LegalLayout eyebrow="Términos y condiciones" kind="terms" locale="es" title="Términos y condiciones de Bigmelo">
      <p>
        Estos términos regulan el acceso y uso de Bigmelo, una plataforma para crear perfiles públicos
        con avatares animados, voz clonada autorizada, información contextual y respuestas generadas
        por inteligencia artificial.
      </p>

      <section>
        <h2>1. Aceptación</h2>
        <p>
          Al crear una cuenta, subir contenido, generar un avatar, clonar una voz, publicar un perfil
          o usar un landing de perfil, aceptas estos términos y nuestra política de privacidad. Si no
          estás de acuerdo, no uses el servicio.
        </p>
      </section>

      <section>
        <h2>2. Requisitos de uso</h2>
        <p>
          Debes tener capacidad legal para contratar y, como mínimo, la mayoría de edad aplicable en tu
          jurisdicción. Si usas Bigmelo en nombre de una empresa, cliente, talento, marca o tercero,
          declaras que tienes autoridad suficiente para obligarlo y para otorgar los permisos descritos
          aquí.
        </p>
      </section>

      <section>
        <h2>3. Autorización sobre imagen, voz y contenido</h2>
        <p>Al subir contenido declaras y garantizas que:</p>
        <ul>
          <li>Tienes todos los derechos y permisos necesarios sobre la imagen, video, audio, voz, texto e información enviada.</li>
          <li>La persona cuya imagen o voz se usa autorizó expresamente la creación de avatar, clonación de voz y publicación del perfil.</li>
          <li>El uso del contenido no viola privacidad, propiedad intelectual, derechos de imagen, derechos de voz, derechos laborales ni derechos de terceros.</li>
          <li>No estás usando el servicio para suplantar, engañar, defraudar, acosar o manipular a otras personas.</li>
        </ul>
      </section>

      <section>
        <h2>4. Licencia para operar el servicio</h2>
        <p>
          Conservas tus derechos sobre el contenido que subes. Sin embargo, otorgas a Bigmelo una
          licencia mundial, no exclusiva y libre de regalías para alojar, copiar, procesar, adaptar,
          transmitir, mostrar y usar tu contenido en la medida necesaria para crear el avatar, clonar y
          reproducir voz, generar respuestas, publicar el perfil, prestar soporte, prevenir abuso y
          operar el servicio.
        </p>
        <p>
          Esta licencia incluye el derecho de enviar contenido a proveedores como Runway, ElevenLabs y
          OpenAI, y a otros subprocesadores necesarios. Si eliminas un perfil o solicitas eliminación,
          dejaremos de usar el contenido para operar ese perfil, salvo copias de respaldo, obligaciones
          legales, registros de seguridad o usos necesarios para investigar abuso.
        </p>
      </section>

      <section>
        <h2>5. Proveedores externos</h2>
        <p>
          Bigmelo usa servicios de terceros para funciones esenciales: Runway para avatar y recursos
          visuales, ElevenLabs para voz y audio, y OpenAI para comprensión de mensajes y generación de
          respuestas. Tu uso del servicio está condicionado a que esos proveedores estén disponibles y
          a que el contenido cumpla sus políticas.
        </p>
        <p>
          No controlamos cambios, interrupciones, límites, decisiones de moderación, reglas de
          retención o políticas de esos proveedores. Podemos suspender, modificar o rechazar una
          generación si un proveedor o nuestro sistema detecta riesgo legal, técnico o de seguridad.
        </p>
      </section>

      <section>
        <h2>6. Perfiles públicos y respuestas de IA</h2>
        <p>
          Los landings de perfil pueden ser públicos. Eres responsable de revisar la información que
          publiques y de mantenerla exacta, lícita y autorizada. Las respuestas del avatar son
          generadas automáticamente a partir del contexto disponible y pueden contener errores,
          omisiones, respuestas similares a las de otros usuarios o contenido no esperado.
        </p>
        <p>
          No debes presentar respuestas generadas como asesoría profesional definitiva, declaración
          humana garantizada, prueba legal, diagnóstico médico, recomendación financiera personalizada
          o decisión automatizada con efectos legales sin revisión humana competente.
        </p>
      </section>

      <section>
        <h2>7. Usos prohibidos</h2>
        <p>No puedes usar Bigmelo para:</p>
        <ul>
          <li>Clonar voces o usar imágenes de terceros sin consentimiento expreso.</li>
          <li>Crear deepfakes engañosos, suplantaciones, fraude, phishing, extorsión o manipulación.</li>
          <li>Generar contenido sexual no consentido, explotación de menores, acoso, amenazas, odio o violencia.</li>
          <li>Difundir desinformación electoral, médica, financiera o legal, o atribuir declaraciones falsas a una persona.</li>
          <li>Usar contenido protegido por propiedad intelectual sin autorización.</li>
          <li>Intentar eludir límites, extraer modelos, acceder sin permiso, interferir con la seguridad o revender acceso no autorizado.</li>
          <li>Subir datos sensibles de terceros, secretos, contraseñas, documentos de identidad o información que no debas compartir.</li>
        </ul>
      </section>

      <section>
        <h2>8. Créditos, planes y pagos</h2>
        <p>
          Algunas funciones consumen créditos o requieren un plan. Los precios, límites, vencimientos,
          renovaciones y funciones incluidas se mostrarán en el sitio o en la oferta aplicable. Salvo
          que la ley exija lo contrario, pagos, créditos consumidos, créditos vencidos y servicios ya
          prestados no son reembolsables.
        </p>
      </section>

      <section>
        <h2>9. Moderación, suspensión y eliminación</h2>
        <p>
          Podemos revisar, rechazar, despublicar, suspender o eliminar perfiles, contenido, voces,
          avatares, respuestas o cuentas cuando creamos razonablemente que existe violación de estos
          términos, riesgo de daño, infracción de derechos, suplantación, fraude, abuso técnico,
          incumplimiento de proveedores o requerimiento legal.
        </p>
      </section>

      <section>
        <h2>10. Propiedad intelectual</h2>
        <p>
          Bigmelo, su diseño, software, marca, interfaz, documentación y tecnología son propiedad de
          Bigmelo o sus licenciantes. No puedes copiar, modificar, descompilar, vender, sublicenciar o
          explotar el servicio salvo lo permitido expresamente.
        </p>
      </section>

      <section>
        <h2>11. Disponibilidad y cambios</h2>
        <p>
          El servicio puede cambiar, degradarse, interrumpirse o dejar de estar disponible por
          mantenimiento, fallos, límites de proveedores, cambios regulatorios o razones comerciales. No
          garantizamos disponibilidad continua ni que las generaciones sean siempre correctas,
          completas, únicas o adecuadas para un fin específico.
        </p>
      </section>

      <section>
        <h2>12. Responsabilidad</h2>
        <p>
          Usas Bigmelo bajo tu responsabilidad. En la máxima medida permitida por la ley, Bigmelo no
          será responsable por daños indirectos, pérdida de ganancias, pérdida de datos, daño
          reputacional, decisiones tomadas con base en respuestas generadas, uso no autorizado de
          contenido que subiste o fallos de proveedores externos.
        </p>
      </section>

      <section>
        <h2>13. Contacto y reportes</h2>
        <p>
          Para reportar suplantación, uso no autorizado de imagen o voz, infracciones de propiedad
          intelectual, contenido ilegal o solicitudes legales, escríbenos a{' '}
          <a href="mailto:legal@bigmelo.com">legal@bigmelo.com</a>.
        </p>
      </section>

      <section>
        <h2>14. Cambios a estos términos</h2>
        <p>
          Podemos actualizar estos términos. Si el cambio es material, podremos notificarlo por el
          sitio, correo o dentro del producto. El uso continuado del servicio después de una
          actualización implica aceptación de la versión vigente, salvo que la ley exija otro
          mecanismo.
        </p>
      </section>
    </LegalLayout>
  );
}

function ExternalProviders({ locale }: { locale: LegalLocale }) {
  if (locale === 'en') {
    return (
      <section>
        <h2>4. Artificial intelligence providers</h2>
        <p>
          To operate the service, we use specialized external providers. By using Bigmelo, you accept
          that the content needed to provide the service may be sent to these providers:
        </p>
        <ul>
          <li>
            <a href="https://runwayml.com/" rel="noreferrer" target="_blank">Runway</a>, for avatar,
            video, image, or other visual asset generation or animation.
          </li>
          <li>
            <a href="https://elevenlabs.io/" rel="noreferrer" target="_blank">ElevenLabs</a>, for
            voice cloning, audio processing, and synthetic voice generation.
          </li>
          <li>
            <a href="https://openai.com/" rel="noreferrer" target="_blank">OpenAI</a>, for
            understanding messages, organizing context, and generating responses.
          </li>
        </ul>
        <p>
          Each provider processes data according to its own terms, privacy policies, security measures,
          processing locations, and retention rules. We may change, add, or replace providers when
          necessary to maintain or improve the service.
        </p>
      </section>
    );
  }

  return (
    <section>
      <h2>4. Proveedores de inteligencia artificial</h2>
      <p>
        Para operar el servicio usamos proveedores externos especializados. Al usar Bigmelo, aceptas
        que el contenido necesario pueda enviarse a estos proveedores para prestar el servicio:
      </p>
      <ul>
        <li>
          <a href="https://runwayml.com/" rel="noreferrer" target="_blank">Runway</a>, para generación
          o animación de avatar, video, imagen u otros recursos visuales.
        </li>
        <li>
          <a href="https://elevenlabs.io/" rel="noreferrer" target="_blank">ElevenLabs</a>, para
          clonación de voz, procesamiento de audio y generación de voz sintética.
        </li>
        <li>
          <a href="https://openai.com/" rel="noreferrer" target="_blank">OpenAI</a>, para comprender
          mensajes, organizar contexto y generar respuestas.
        </li>
      </ul>
      <p>
        Cada proveedor procesa datos conforme a sus propias condiciones, políticas de privacidad,
        medidas de seguridad, ubicaciones de procesamiento y reglas de retención. Podemos cambiar,
        agregar o sustituir proveedores cuando sea necesario para mantener o mejorar el servicio.
      </p>
    </section>
  );
}

function LegalLayout({ children, eyebrow, kind, locale, title }: LegalLayoutProps) {
  const copy = legalCopy[locale];
  const privacyPath = locale === 'es' ? '/privacidad' : '/privacy';
  const termsPath = locale === 'es' ? '/terminos' : '/terms';
  const spanishPath = kind === 'privacy' ? '/privacidad' : '/terminos';
  const englishPath = kind === 'privacy' ? '/privacy' : '/terms';

  useEffect(() => {
    document.documentElement.lang = locale;
    document.title = `${title} | Bigmelo`;
    window.scrollTo({ top: 0, behavior: 'auto' });
  }, [locale, title]);

  return (
    <main className="legal-page">
      <header className="legal-topbar">
        <a className="brand" href="/" aria-label="Bigmelo">
          <img className="brand-logo" alt="Bigmelo" src={bigmeloLogo} />
        </a>

        <div className="legal-topbar-actions">
          <nav className="legal-nav" aria-label={locale === 'es' ? 'Navegación legal' : 'Legal navigation'}>
            <a href="/">{copy.home}</a>
            <a href={privacyPath}>{copy.privacy}</a>
            <a href={termsPath}>{copy.terms}</a>
          </nav>

          <div className="legal-language-switch" aria-label={locale === 'es' ? 'Idioma' : 'Language'}>
            <a className={locale === 'es' ? 'is-active' : ''} href={spanishPath}>ES</a>
            <a className={locale === 'en' ? 'is-active' : ''} href={englishPath}>EN</a>
          </div>
        </div>
      </header>

      <article className="legal-document">
        <p className="eyebrow">{eyebrow}</p>
        <h1>{title}</h1>
        <p className="legal-updated">{copy.updated}</p>
        {children}
      </article>

      <footer className="legal-footer">
        <a href="/">Bigmelo</a>
        <span>{copy.footer}</span>
      </footer>
    </main>
  );
}
